import { getAssetUrl } from '../utils/assetUrl';

export const FALLBACK_PRODUCTS = [
  {
    _id: '66d1f0a1b2c3d4e5f6000001',
    id: 'prod-1',
    name: 'The Nestling Cable Knit Romper',
    slug: 'nestling-cable-knit-romper',
    subtitle: 'Heirloom Organic Baby Romper with Natural Coconut Buttons',
    description: 'Charming vintage-inspired cable-knit baby romper crafted from 100% GOTS-certified combed organic cotton. Features an envelope neckline for gentle dressing, natural coconut husk buttons, and ultra-soft ribbed cuffs that gently hug tiny ankles without pinching.',
    price: 48,
    compareAtPrice: 62,
    category: 'rompers',
    ageGroup: 'baby',
    ageRange: '0 – 12 Months',
    badge: 'Pure Organic Knit',
    fabric: '100% GOTS Organic Combed Cotton',
    fabricDetails: ['Ultra-gentle 12-gauge combed knit', 'Hypoallergenic and dye-free option available', 'Pre-shrunk organic yarn'],
    certifications: ['GOTS Certified Organic', 'OEKO-TEX Standard 100 Class I (Baby Safe)'],
    colors: [
      { name: 'Dusty Rose Blossom', hex: '#D59691' },
      { name: 'Pure Feather Creme', hex: '#FAF7F2' },
      { name: 'Warm Oat Nest', hex: '#DFCEBE' },
    ],
    sizes: [
      { size: '0 – 3 Months', stock: 15 },
      { size: '3 – 6 Months', stock: 20 },
      { size: '6 – 12 Months', stock: 18 },
    ],
    images: [getAssetUrl('images/baby.jpg'), getAssetUrl('images/hero.jpg')],
    featuredImage: getAssetUrl('images/baby.jpg'),
    features: [
      'Diaper-friendly snap bottom with nickel-free closures',
      'Seamless interior neck label (zero itch guarantee)',
      'Expandable shoulder envelope design',
      'Machine washable on gentle wool cycle',
    ],
    rating: 4.9,
    numReviews: 38,
    reviews: [
      {
        id: 'rev-1',
        name: 'Elena Rostova',
        rating: 5,
        comment: 'The softest baby romper we own. My 4-month-old sleeps peacefully in it and the coconut buttons are exquisite!',
        childAge: '4 Months',
        date: '2026-08-14',
      },
      {
        id: 'rev-2',
        name: 'Claire Thornton',
        rating: 5,
        comment: 'Heirloom quality through and through. The cotton knit has held up perfectly after multiple delicate washes.',
        childAge: '6 Months',
        date: '2026-08-20',
      },
    ],
    isFeatured: true,
    totalStock: 53,
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000002',
    id: 'prod-2',
    name: 'Fledgling Washed Linen Dungarees',
    slug: 'fledgling-washed-linen-dungarees',
    subtitle: 'Relaxed Silhouette Overalls for Active Toddlers',
    description: 'Artisan garment-washed European flax linen dungarees tailored for unrestricted playtime. Equipped with double wooden adjustable strap buttons to grow with your toddler and reinforced knee patches designed to survive first crawls and garden wanders.',
    price: 54,
    compareAtPrice: 68,
    category: 'dungarees',
    ageGroup: 'toddler',
    ageRange: '1 – 3 Years',
    badge: 'European Flax Linen',
    fabric: '100% Pre-Washed Normandy Linen & Organic Voile Lining',
    fabricDetails: ['Zero synthetic fibers', 'Naturally antimicrobial & thermoregulating', 'Gets softer with every wash'],
    certifications: ['European Flax® Certified', 'GOTS Certified Organic Lining'],
    colors: [
      { name: 'Sage Meadow', hex: '#8A977B' },
      { name: 'Warm Terracotta', hex: '#C2847A' },
      { name: 'Natural Oatmeal', hex: '#DFCEBE' },
    ],
    sizes: [
      { size: '12 – 18 Months', stock: 12 },
      { size: '18 – 24 Months', stock: 14 },
      { size: '2 – 3 Years', stock: 16 },
    ],
    images: [getAssetUrl('images/toddler.jpg'), getAssetUrl('images/hero.jpg')],
    featuredImage: getAssetUrl('images/toddler.jpg'),
    features: [
      'Dual-button adjustable shoulder straps (+2 inches growth ease)',
      'Hidden inner leg snap buttons for quick diaper changes',
      'Dual deep pocket nooks for collected nature treasures',
    ],
    rating: 4.8,
    numReviews: 24,
    reviews: [
      {
        id: 'rev-3',
        name: 'Hannah Davies',
        rating: 5,
        comment: 'So durable and stylish! My 2-year-old lives in these dungarees.',
        childAge: '2 Years',
        date: '2026-08-18',
      },
    ],
    isFeatured: true,
    totalStock: 42,
    createdAt: '2026-08-02T00:00:00.000Z',
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000003',
    id: 'prod-3',
    name: 'Meadow Blossom Tiered Dress',
    slug: 'meadow-blossom-tiered-dress',
    subtitle: 'Botanical Dyed Organic Cotton Dress with Flutter Sleeves',
    description: 'Whimsical three-tier silhouette with gentle flutter sleeves, dyed using sustainable extracts of madder root and chamomile flowers. An effortless everyday dress that spins beautifully and lets delicate young skin breathe under the summer sunshine.',
    price: 58,
    compareAtPrice: 72,
    category: 'dresses',
    ageGroup: 'little',
    ageRange: '4 – 6 Years',
    badge: 'Botanical Plant Dyed',
    fabric: '100% GOTS Organic Crinkle Gauze Cotton',
    fabricDetails: ['Double-layer breathable gauze', 'Zero heavy metals or toxic mordants', 'Self-lined bodice for maximum opacity'],
    certifications: ['GOTS Certified Organic', 'Soil Association Organic Standard'],
    colors: [
      { name: 'Petal Blush Pink', hex: '#D59691' },
      { name: 'Olive Sprout', hex: '#8A977B' },
      { name: 'Sunbeam Ochre', hex: '#E8C587' },
    ],
    sizes: [
      { size: '3 – 4 Years', stock: 10 },
      { size: '4 – 5 Years', stock: 12 },
      { size: '5 – 6 Years', stock: 15 },
    ],
    images: [getAssetUrl('images/little_kids.jpg'), getAssetUrl('images/hero.jpg')],
    featuredImage: getAssetUrl('images/little_kids.jpg'),
    features: [
      'Gentle elastic smocking at back neckline for self-dressing ease',
      'Real mother-of-pearl buttons at back keyhole closure',
      'Twin concealed side seam pockets',
    ],
    rating: 5.0,
    numReviews: 19,
    reviews: [
      {
        id: 'rev-4',
        name: 'Maria S.',
        rating: 5,
        comment: 'My daughter refused to take this off all weekend. The botanical color is even prettier in person!',
        childAge: '5 Years',
        date: '2026-08-21',
      },
    ],
    isFeatured: true,
    totalStock: 37,
    createdAt: '2026-08-03T00:00:00.000Z',
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000004',
    id: 'prod-4',
    name: 'Junior Aviator Organic Knit Pullover',
    slug: 'junior-aviator-organic-knit-pullover',
    subtitle: 'Timeless Waffle Knit Sweater for Growing Explorers',
    description: 'Chunky yet breathable mid-weight thermal pullover designed for young explorers embarking on breezy outdoor adventures. Crafted with rib-knit cuffs, a crew neckline, and dropped shoulders for an effortlessly chic and cozy layering piece.',
    price: 64,
    compareAtPrice: 78,
    category: 'knitwear',
    ageGroup: 'junior',
    ageRange: '7 – 10 Years',
    badge: 'Chunky Organic Cotton',
    fabric: '100% Organic Peruvian Pima Cotton Knit',
    fabricDetails: ['Ultra-long staple Pima cotton', 'Non-pilling heirloom knit construction', 'Natural thermal insulation'],
    certifications: ['GOTS Certified Organic', 'Fair Trade Certified™ Factory'],
    colors: [
      { name: 'Warm Taupe Sand', hex: '#735A4B' },
      { name: 'Forest Sage', hex: '#5C674F' },
      { name: 'Cream Chalk', hex: '#FAF7F2' },
    ],
    sizes: [
      { size: '6 – 7 Years', stock: 10 },
      { size: '7 – 8 Years', stock: 14 },
      { size: '9 – 10 Years', stock: 12 },
    ],
    images: [getAssetUrl('images/big_kids.jpg'), getAssetUrl('images/hero.jpg')],
    featuredImage: getAssetUrl('images/big_kids.jpg'),
    features: [
      'Reinforced shoulder seams that maintain shape through dozens of seasons',
      'Ultra-soft brushed interior for all-day cozy comfort',
      'Unisex timeless styling for passing down between siblings',
    ],
    rating: 4.9,
    numReviews: 31,
    reviews: [
      {
        id: 'rev-5',
        name: 'David K.',
        rating: 5,
        comment: 'Outstanding quality. Extremely soft and heavyweight without feeling itchy.',
        childAge: '8 Years',
        date: '2026-08-16',
      },
    ],
    isFeatured: true,
    totalStock: 36,
    createdAt: '2026-08-04T00:00:00.000Z',
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000005',
    id: 'prod-5',
    name: 'Mommy & Me Heirloom Linen Pair',
    slug: 'mommy-and-me-heirloom-linen-pair',
    subtitle: 'Coordinated French Linen Dresses for Mother & Child',
    description: 'Create unforgettable family moments with this matched set of heirloom tiered linen dresses. Both garments are crafted from lightweight stonewashed French linen in our signature Dusty Rose and Sage colorways, featuring pockets on both adult and child garments.',
    price: 138,
    compareAtPrice: 165,
    category: 'sets',
    ageGroup: 'mommy-me',
    ageRange: 'Mother & Child Set',
    badge: 'Mommy & Me Capsule',
    fabric: '100% French Washed Flax Linen',
    fabricDetails: ['Pre-washed for effortless drape', 'Includes 1 Adult Midi Dress + 1 Child Dress of your choice', 'Breathable & non-static'],
    certifications: ['European Flax® Certified', 'OEKO-TEX Standard 100 Class I'],
    colors: [
      { name: 'Blush & Dune Rose', hex: '#D59691' },
      { name: 'Sage & Olive Duo', hex: '#8A977B' },
    ],
    sizes: [
      { size: 'Mom S + Child 2-3Y', stock: 6 },
      { size: 'Mom M + Child 4-5Y', stock: 8 },
      { size: 'Mom L + Child 6-7Y', stock: 5 },
    ],
    images: [getAssetUrl('images/mommy_me.jpg'), getAssetUrl('images/hero.jpg')],
    featuredImage: getAssetUrl('images/mommy_me.jpg'),
    features: [
      'Coordinated color palettes and matching coconut button accents',
      'Both dresses feature functional deep side pockets',
      'Arrives in our luxury embroidered gift keepsake box',
    ],
    rating: 5.0,
    numReviews: 42,
    reviews: [
      {
        id: 'rev-6',
        name: 'Sophie Laurent',
        rating: 5,
        comment: 'We wore these for our family portraits and received endless compliments! The fabric is breathtaking.',
        childAge: '4 Years',
        date: '2026-08-25',
      },
    ],
    isFeatured: true,
    totalStock: 19,
    createdAt: '2026-08-05T00:00:00.000Z',
  },
];
