export const FALLBACK_PRODUCTS = [
  {
    _id: '66d1f0a1b2c3d4e5f6000001',
    id: 'prod-1',
    name: 'The Nestling Cable Knit Romper',
    slug: 'nestling-cable-knit-romper',
    subtitle: 'Heirloom Organic Baby Romper with Natural Coconut Buttons',
    description: 'Charming vintage-inspired cable-knit baby romper crafted from 100% GOTS-certified combed organic cotton. Features an envelope neckline for gentle dressing, natural coconut husk buttons, and ultra-soft ribbed cuffs that gently hug tiny ankles without pinching.',
    price: 48,
    compareAtPrice: 62,
    category: 'rompers',
    ageGroup: 'baby',
    ageRange: '0 – 12 Months',
    badge: 'Pure Organic Knit',
    fabric: '100% GOTS Organic Combed Cotton',
    fabricDetails: ['Ultra-gentle 12-gauge combed knit', 'Hypoallergenic and dye-free option available', 'Pre-shrunk organic yarn'],
    certifications: ['GOTS Certified Organic', 'OEKO-TEX Standard 100 Class I (Baby Safe)'],
    colors: [
      { name: 'Dusty Rose Blossom', hex: '#D59691' },
      { name: 'Pure Feather Creme', hex: '#FAF7F2' },
      { name: 'Warm Oat Nest', hex: '#DFCEBE' },
    ],
    sizes: [
      { size: '0 – 3 Months', stock: 15 },
      { size: '3 – 6 Months', stock: 20 },
      { size: '6 – 12 Months', stock: 18 },
    ],
    images: ['/images/baby.jpg', '/images/hero.jpg'],
    featuredImage: '/images/baby.jpg',
    features: [
      'Diaper-friendly snap bottom with nickel-free closures',
      'Seamless interior neck label (zero itch guarantee)',
      'Expandable shoulder envelope design',
      'Machine washable on gentle wool cycle',
    ],
    rating: 4.9,
    numReviews: 38,
    reviews: [
      {
        id: 'rev-1',
        name: 'Elena Vance (Mom to Leo, 4M)',
        rating: 5,
        comment: 'The softest baby romper we own! The knit feels extraordinarily luxurious and has held up beautifully through several gentle washes.',
        verifiedPurchase: true,
        childAge: '4 Months',
        createdAt: '2026-08-15T10:00:00Z',
      },
      {
        id: 'rev-2',
        name: 'Claire Kensington',
        rating: 5,
        comment: 'The coconut buttons and dusty rose hue are even more stunning in person. Perfect for newborn photography.',
        verifiedPurchase: true,
        childAge: '2 Months',
        createdAt: '2026-08-18T14:30:00Z',
      },
    ],
    isFeatured: true,
    isNewArrival: true,
    isBestseller: true,
    totalStock: 53,
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000002',
    id: 'prod-2',
    name: 'Wanderer French Linen Dungarees & Henley Set',
    slug: 'wanderer-linen-dungarees-henley-set',
    subtitle: 'Durable Washed Flax Overalls with Cozy Waffle Top',
    description: 'Designed for curious toddlers and active explorers. Pure French washed linen dungarees featuring reinforced double-knee panels and grow-with-me adjustable shoulder straps, paired with a cloud-soft organic waffle knit henley shirt.',
    price: 64,
    compareAtPrice: 78,
    category: 'dungarees',
    ageGroup: 'toddler',
    ageRange: '1 – 3 Years',
    badge: 'French Flax Linen',
    fabric: 'Pure French Washed Linen + Organic Waffle',
    fabricDetails: ['Enzyme-washed European flax linen', 'Naturally temperature-regulating', 'Heavyweight waffle knit inner'],
    certifications: ['Masters of Linen Certified', 'OEKO-TEX Standard 100'],
    colors: [
      { name: 'Earthy Chestnut', hex: '#735A4B' },
      { name: 'Sage Meadow', hex: '#8A977B' },
      { name: 'Warm Oat Nest', hex: '#DFCEBE' },
    ],
    sizes: [
      { size: '12 – 18 Months', stock: 12 },
      { size: '18 – 24 Months', stock: 16 },
      { size: '2 – 3 Years', stock: 14 },
    ],
    images: ['/images/toddler.jpg', '/images/hero.jpg'],
    featuredImage: '/images/toddler.jpg',
    features: [
      'Two-stage adjustable button straps (grows with your toddler)',
      'Reinforced knee patches for tumbling and sandbox play',
      'Elasticated back waist for quick potty training access',
      'Deep treasure collection pockets',
    ],
    rating: 4.85,
    numReviews: 29,
    reviews: [
      {
        id: 'rev-3',
        name: 'Sarah Montgomery (Mom of 2)',
        rating: 5,
        comment: 'Incredible craftsmanship. The linen gets noticeably softer with every wash and the knees are truly durable!',
        verifiedPurchase: true,
        childAge: '2 Years',
        createdAt: '2026-08-10T12:00:00Z',
      },
    ],
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    totalStock: 42,
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000003',
    id: 'prod-3',
    name: 'Songbird Botanical Embroidered Linen Dress',
    slug: 'songbird-botanical-embroidered-dress',
    subtitle: 'Handcrafted Heirloom Dress with Flutter Sleeves',
    description: 'An airy, enchanting dress made from breathable slub linen. Delicately hand-embroidered with mammaBird mother-and-chick botanical motifs around the yoke, accompanied by breezy flutter sleeves and natural mother-of-pearl back buttons.',
    price: 58,
    compareAtPrice: 72,
    category: 'dresses',
    ageGroup: 'little',
    ageRange: '4 – 6 Years',
    badge: 'Hand-Embroidered',
    fabric: 'Organic Slub Linen & Cotton Lace',
    fabricDetails: ['Plant-dyed botanical fibers', 'Zero synthetic polyester lining', 'Hand-stitched bird illustration'],
    certifications: ['GOTS Certified Organic', 'Fair Trade Certified'],
    colors: [
      { name: 'Dusty Rose Blossom', hex: '#D59691' },
      { name: 'Sage Meadow', hex: '#8A977B' },
      { name: 'Pure Feather Creme', hex: '#FAF7F2' },
    ],
    sizes: [
      { size: '3 – 4 Years', stock: 10 },
      { size: '4 – 5 Years', stock: 15 },
      { size: '5 – 6 Years', stock: 12 },
    ],
    images: ['/images/little_kids.jpg', '/images/hero.jpg'],
    featuredImage: '/images/little_kids.jpg',
    features: [
      'Signature mother bird heirloom embroidery',
      'Comfort-stretch elastic underarm for all-day twirling',
      'Mother-of-pearl button closure',
      'Includes matching fabric hair ribbon',
    ],
    rating: 4.95,
    numReviews: 44,
    reviews: [
      {
        id: 'rev-4',
        name: 'Marianne Dubois',
        rating: 5,
        comment: 'My 5-year old daughter refuses to take this off. It looks like a fairytale vintage piece. 10/10 quality.',
        verifiedPurchase: true,
        childAge: '5 Years',
        createdAt: '2026-08-20T09:15:00Z',
      },
    ],
    isFeatured: true,
    isNewArrival: true,
    isBestseller: true,
    totalStock: 37,
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000004',
    id: 'prod-4',
    name: 'The Young Aviator Chunky Knit & Chinos',
    slug: 'young-aviator-chunky-knit-and-chinos',
    subtitle: 'Sophisticated Relaxed Sweater with Tailored Linen Trousers',
    description: 'Elevated casualwear tailored for active minds and growing juniors. Features a relaxed heavyweight cotton fisherman pullover with ribbed raglan sleeves paired with adjustable drawstring linen chinos.',
    price: 72,
    compareAtPrice: 89,
    category: 'knitwear',
    ageGroup: 'junior',
    ageRange: '7 – 10 Years',
    badge: 'Heirloom Edition',
    fabric: 'Heavyweight Ribbed Cotton & Relaxed Flax',
    fabricDetails: ['Garment dyed with botanical pigments', 'Tagless sensory-friendly neckline', 'Anti-pilling organic weave'],
    certifications: ['GOTS Certified Organic', 'OEKO-TEX Standard 100'],
    colors: [
      { name: 'Warm Oat Nest', hex: '#DFCEBE' },
      { name: 'Earthy Chestnut', hex: '#735A4B' },
      { name: 'Sage Meadow', hex: '#8A977B' },
    ],
    sizes: [
      { size: '6 – 7 Years', stock: 14 },
      { size: '7 – 8 Years', stock: 18 },
      { size: '9 – 10 Years', stock: 12 },
    ],
    images: ['/images/big_kids.jpg', '/images/hero.jpg'],
    featuredImage: '/images/big_kids.jpg',
    features: [
      'Tailored elastic waistband with herringbone cotton drawstring',
      'Reinforced side seam pockets with coin detail',
      'Breathable organic thermal properties for autumn & winter',
      'Pre-washed against shrinkage',
    ],
    rating: 4.8,
    numReviews: 21,
    reviews: [
      {
        id: 'rev-5',
        name: 'David & Rachel Thorne',
        rating: 5,
        comment: 'Finding stylish, organic clothes for a 9-year-old boy is tough. mammaBird nailed the modern aesthetic without sacrificing organic materials!',
        verifiedPurchase: true,
        childAge: '9 Years',
        createdAt: '2026-08-12T16:45:00Z',
      },
    ],
    isFeatured: true,
    isNewArrival: false,
    isBestseller: false,
    totalStock: 44,
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000005',
    id: 'prod-5',
    name: 'Mommy & Me Meadow Blossom Tiered Gown Set',
    slug: 'mommy-and-me-meadow-blossom-gown-set',
    subtitle: 'Harmonious Mother & Child Matching Pure Linen Dresses',
    description: 'Create unforgettable family memories with our signature matching heirloom set. Includes a tiered maxi silhouette for mom featuring discreet nursing-friendly hidden side zippers, and an identical miniature tiered gown for your little one.',
    price: 135,
    compareAtPrice: 165,
    category: 'sets',
    ageGroup: 'mommy-me',
    ageRange: 'Mother & Child Set',
    badge: 'Matching Heirlooms',
    fabric: 'Tiered Organic Washed Linen',
    fabricDetails: ['100% Breathable European flax', 'Lined with ultra-soft organic voile', 'Delicate lace hem insets'],
    certifications: ['GOTS Certified Organic', 'OEKO-TEX Standard 100'],
    colors: [
      { name: 'Dusty Rose Blossom', hex: '#D59691' },
      { name: 'Pure Feather Creme', hex: '#FAF7F2' },
      { name: 'Sage Meadow', hex: '#8A977B' },
    ],
    sizes: [
      { size: 'Mom S + Child 0-12M', stock: 8 },
      { size: 'Mom S + Child 1-3Y', stock: 10 },
      { size: 'Mom M + Child 1-3Y', stock: 12 },
      { size: 'Mom M + Child 4-6Y', stock: 15 },
      { size: 'Mom L + Child 4-6Y', stock: 9 },
      { size: 'Mom L + Child 7-10Y', stock: 7 },
    ],
    images: ['/images/mommy_me.jpg', '/images/hero.jpg'],
    featuredImage: '/images/mommy_me.jpg',
    features: [
      'Complete set includes 1 Mother Gown + 1 Child Matching Dress',
      'Hidden invisible nursing zippers on mother gown',
      'Flutter ruffles with hand-hemmed borders',
      'Comes packaged in an embroidered keepsake linen storage pouch',
    ],
    rating: 5.0,
    numReviews: 52,
    reviews: [
      {
        id: 'rev-6',
        name: 'Jessica Alverez (Mom to Mia, 3Y)',
        rating: 5,
        comment: 'We wore these for our family portraits and received endless compliments! The linen drape is breathtaking and so comfortable to wear all day.',
        verifiedPurchase: true,
        childAge: '3 Years',
        createdAt: '2026-08-22T11:20:00Z',
      },
    ],
    isFeatured: true,
    isNewArrival: true,
    isBestseller: true,
    totalStock: 61,
  },
  {
    _id: '66d1f0a1b2c3d4e5f6000006',
    id: 'prod-6',
    name: 'First Flight Quad-Layer Organic Muslin Swaddle',
    slug: 'first-flight-quad-layer-muslin-swaddle',
    subtitle: 'Ultra-Breathable Large Gauze Blanket & Matching Bonnet',
    description: 'Generously sized (120 x 120 cm) four-layer open-weave organic muslin blanket featuring delicate water-based botanical prints. Includes a coordinating newborn bonnet with gentle chin tie.',
    price: 34,
    compareAtPrice: 42,
    category: 'accessories',
    ageGroup: 'baby',
    ageRange: '0 – 12 Months',
    badge: 'Quad-Layer Muslin',
    fabric: 'Quad-Layer Organic Muslin',
    fabricDetails: ['GOTS Certified Organic cotton gauze', 'Water-based non-toxic vegetable ink', 'Gets fluffier with every tumble dry'],
    certifications: ['GOTS Certified Organic', 'Hypoallergenic Certified'],
    colors: [
      { name: 'Pure Feather Creme', hex: '#FAF7F2' },
      { name: 'Dusty Rose Blossom', hex: '#D59691' },
      { name: 'Sage Meadow', hex: '#8A977B' },
    ],
    sizes: [
      { size: 'One Size (120x120cm)', stock: 35 },
    ],
    images: ['/images/baby.jpg', '/images/hero.jpg'],
    featuredImage: '/images/baby.jpg',
    features: [
      'Multi-use: Swaddle, stroller canopy, nursing drape, or play mat',
      'Ultra-breathable quad weave prevents overheating',
      'Includes matching newborn bonnet with soft ties',
      'Signature mammaBird woven heirloom label',
    ],
    rating: 4.92,
    numReviews: 67,
    reviews: [
      {
        id: 'rev-7',
        name: 'Emily Watson',
        rating: 5,
        comment: 'The softest blanket we own. Our baby falls asleep instantly when wrapped in this cloud-like muslin.',
        verifiedPurchase: true,
        childAge: '1 Month',
        createdAt: '2026-08-05T18:10:00Z',
      },
    ],
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    totalStock: 35,
  },
];
